source 'https://rubygems.org'

gem 'calabash', '2.0.0.prelegacy4'
gem 'cucumber', '~> 2.0'
gem 'slowhandcuke', '>= 0.0.3', '< 1.0'
gem 'rspec-expectations'
gem 'pusher'
gem 'data_magic'
gem 'page-object'
gem 'require_all'
gem 'allure-cucumber'