# config/cucumber.yml
#YAML Template
<%
# Android
android_home = "/usr/local/opt/android-sdk" # installed from homebrew
android_phone = "" # device adb id
android_emu = "emulator-5554" # emulator ADB id
android_app = "" # .apk file

# IOS
device_ip = "http://iphone.local:37265" # Hostname of iphone
ip = "http://192.168.10.132:37265" # IP of iphone
iphone = "" # Device id
ios_app = "" # .ipa file
app_location = "" # .app file
%>
---
#Base Profiles
rerun: -f rerun # Rerun failed scenarios
verbose: CAL_DEBUG=1 # Calabash debugging output
format_html: --format html --out report.html # HTML reporting
format_json: --format json --out report.json # JSON reporting
reset_between_scenarios: RESET_BETWEEN_SCENARIOS=1 # Reset app/phone between scenarios
device_common: -r features/support -r features/step_definitions -r features/pages --format pretty --tags ~@wip --tags ~@manual --format AllureCucumber::Formatter --out blah.html

#Android Profiles
android: PLATFORM=android -r features/android/pages CAL_DEVICE_ID=<%= android_phone  %> CAL_APP=<%= android_app %> -p device_common --tags ~@ios-only

#IOS Profiles
ios: PLATFORM=ios -r features/ios/pages CAL_DEVICE_ID=<%= iphone %> CAL_ENDPOINT=<%= ip %> CAL_APP=<%= ios_app %>  -p device_common  --tags ~@android-only


